version: 2.1
jobs:
  build:
    docker:
      - imgage: golang:latest
      working_directory: /go/src/github.com/Wyntter/aula_CI
      steps:
      - checkout
      - run:
        name: Run tests
        command: go test -v
